application: calendarmailer
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: genfiles/closure-gen

- url: .*
  script: main.py
